repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black docci tests
        pass_filenames: false
        language: system
      - id: pytest
        name: pytest
        entry: poetry run pytest
        pass_filenames: false
        language: system
      - id: mypy
        name: mypy
        entry: poetry run mypy docci tests
        pass_filenames: false
        language: system
      - id: flake8
        name: flake8
        entry: poetry run flake8 docci tests
        pass_filenames: false
        language: system
      - id: docstrings
        name: docstrings
        entry: poetry run pydocstyle docci
        pass_filenames: false
        language: system
      - id: requirements
        name: requirements
        entry: poetry export --dev --without-hashes -f requirements.txt > requirements.txt
        pass_filenames: false
        language: system